[mypy]
python_version = 3.12
files = service
check_untyped_defs = True
ignore_missing_imports = True
exclude = ^service/(tests|alembic)/

[mypy-torch_geometric.*,pandas.*,scipy.*,sklearn.*,pyarrow.*,gnn,utils,train_sg_neighbor,riskgnn.*]
follow_imports = skip
